Fixed a bug that prevented resetting DOTFILES_ROOT variable.

diff --git a/bin/dotfiles-install b/bin/dotfiles-install
--- a/bin/dotfiles-install
+++ b/bin/dotfiles-install
@@ -3,6 +3,10 @@ set -e
 
 # Include the utlities
 _path="${BASH_SOURCE%/*}"
+if [ ! -f $_path/lib/utils.sh ]; then
+    echo "Could not find utils."
+    exit 1
+fi
 source $_path/lib/utils.sh
 
 # Parse arguments
