git-migrate: Improved matching and added new options.

diff --git a/bin/git-migrate b/bin/git-migrate
--- a/bin/git-migrate
+++ b/bin/git-migrate
@@ -1,6 +1,12 @@
 #!/usr/bin/env bash
 
 _args=$#
+_logs=();
+if [ ! -t 0 ]; then
+    while read -r line; do
+        _logs+=($line)
+    done
+fi
 
 for i in "$@"; do
     case $i in
@@ -57,7 +63,7 @@ _dst=$(realpath "${_dst/#\~/$HOME}")
 if [[ -z $_test ]]; then
     echo
     echo "WARNING: This operation will reset your --src repository and wipeout --dst."
-    read -p "         Are you sure you want to continue? [y/n] " -n 1 -r
+    read -p "         Are you sure you want to continue? [y/n] " -n 1 REPLY < /dev/tty
     echo
     [[ ! $REPLY =~ ^[Yy]$ ]] && exit 1
 fi
@@ -69,9 +75,22 @@ function _git {
 
 function _find {
     ([[ -z $_filter ]]\
-        && find $_src -mindepth 1 -maxdepth 1 -not -name ".git" -exec $@ \;\
-        || find $_src -mindepth 1 -name "$_filter" -not -name ".git" -exec $@ \;\
+        && find $_src -type f -mindepth 1 -maxdepth 1 -not -name ".git" $@ \
+        || find $_src -type f -mindepth 1 -name "$_filter" -not -name ".git" $@ \
     )
+}
+
+function _list {
+    _format='%h_»_%at_»_%an_»_%ae_»_%s'
+    if [[ ${#_logs[@]} -gt 0 ]]; then
+        # so commits were sent (supposedly) print each log individually
+        for _log in ${_logs[@]}; do
+            _git $_src log -n1 --format=$_format $_log
+        done
+    else
+        # no special logging command was sent, log normally.
+        _git $_src log --format=$_format --grep=$_grep
+    fi
 }
 
 # determine the current commit on given repository
@@ -93,8 +112,7 @@ else
 fi
 
 # get the list of commits to be migrated and iterate them
-_format='%h_»_%at_»_%an_»_%ae_»_%s'
-IFS=$'\n' _commits=$(_git $_src log --format=$_format --grep=$_grep | tac)
+IFS=$'\n' _commits=$(_list| tac)
 for _commit in ${_commits[@]}; do
 
     # split each line into using custom separator and store as an array named the same
@@ -107,7 +125,9 @@ for _commit in ${_commits[@]}; do
     [[ ! -z "$_sed" ]] && _body=$(sed $_sed <<< "$_body")
 
     # checkout to corresponding commit
-    _git $_src checkout $_hash &> /dev/null || continue
+    _git $_src clean -dfx  &> /dev/null && \
+    _git $_src reset --hard $_hash &> /dev/null ||\
+        (echo  "Error reseting commit in $_hash" && exit 1)
 
     # if running in dry-mode just output the matched commits as JSON
     if [[ ! -z $_test ]]; then
@@ -118,20 +138,28 @@ for _commit in ${_commits[@]}; do
             '"mail": "'$_mail'",'\
             '"body": "'$_body'",'\
             '"cont": ['\
-                $(_find echo "\""{}"\",") \
+                $(_find --exec echo "\""{}"\"," \;) \
             '""]'\
         '},'
         continue
     fi
 
+    # skip if no files pass the filter.
+    [[ $(_find -print | wc -l) -eq 0 ]] && continue;
+
     # remove all files from destination
-    find $_dst -mindepth 1 -maxdepth 1 -not -name ".git" -exec rm -Rf {} \; || continue
+    find $_dst -mindepth 1 -maxdepth 1 -not -name ".git" -exec rm -Rf {} \;
 
-    # copy the corresponding files to destination
-    _find cp -Rf {} $_dst/
+    #  the corresponding files to destination
+    for _fil in $(_find -print); do
+        _dir=$(dirname $_fil)
+        _dir=${_dir/$_src/$_dst}
+        mkdir -p $_dir
+        mv -f $_fil $_dir/
+    done
 
-    # Add everything on destination and create a clone of the commit
-    _git $_dst add -A || continue
+    _git $_dst add -A
+    [ $(_git $_dst diff --cached --numstat | wc -l) -eq 0 ] && continue
 
     echo
     GIT_AUTHOR_NAME=$_name\
@@ -140,7 +168,7 @@ for _commit in ${_commits[@]}; do
     GIT_COMMITTER_NAME=$_name\
     GIT_COMMITTER_EMAIL=$_mail\
     GIT_COMMITTER_DATE=$_date\
-        _git $_dst commit -m "$_body" || continue
+        _git $_dst commit -m "$_body"
 
 done
 
@@ -148,5 +176,7 @@ done
 # just add a last empty member.
 [[ ! -z $_test ]] && echo -e " {}\n]" && exit 0
 
-_git $_src checkout $_ref
+echo
+echo
+_git $_src reset --hard $_ref
 
